name: Oreacle Bot Monitor

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Create tmp directory
      run: mkdir -p tmp
      
    - name: Run monitor (single cycle)
      env:
        MANIFOLD_API_KEY: ${{ secrets.MANIFOLD_API_KEY }}
        MARKET_SLUG: ${{ secrets.MARKET_SLUG }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OREACLE_MODEL: ${{ secrets.OREACLE_MODEL }}
        OREACLE_MIN_CONFIDENCE: ${{ secrets.OREACLE_MIN_CONFIDENCE }}
        OREACLE_COMMENT_ONLY: ${{ secrets.OREACLE_COMMENT_ONLY }}
        OREACLE_LOG: INFO
        OREACLE_DB: ./tmp/oreacle.db
      run: |
        python src/monitor_single.py