name: Test Bot Setup

on:
  workflow_dispatch:  # Manual trigger only
  pull_request:       # Test on PRs

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Test imports
      run: |
        python -c "
        import sys
        sys.path.append('src')
        
        # Test basic imports
        from models import Extraction, Evidence
        from prefilter import enhanced_relevance_check
        from client import ManifoldClient, Comment
        import yaml
        
        # Test phrasebook loading
        with open('phrasebook.yml', 'r') as f:
            phrasebook = yaml.safe_load(f)
        
        print('✅ All imports successful')
        print(f'✅ Phrasebook loaded with {len(phrasebook)} categories')
        "
        
    - name: Test configuration (without secrets)
      run: |
        python -c "
        import os
        import sys
        sys.path.append('src')
        
        # Test configuration loading without actual API keys
        os.environ['MANIFOLD_API_KEY'] = 'test_key'
        os.environ['MARKET_SLUG'] = 'test_slug'
        os.environ['OREACLE_COMMENT_ONLY'] = '1'
        os.environ['OREACLE_LOG'] = 'INFO'
        
        print('✅ Configuration test passed')
        print('✅ Ready for production deployment with real API keys')
        "